# Generated by Django 2.0.10 on 2020-02-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnnitem',
            name='published_date_raw',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='youtubeitem',
            name='published_date_raw',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
