# Generated by Django 2.0.10 on 2020-03-22 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='USAStateCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=None, default='code', max_length=255, null=True, unique=True)),
                ('english', models.CharField(blank=None, default='english', max_length=255, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='USAStateItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.IntegerField(blank=None, default=0, null=True)),
                ('death', models.IntegerField(blank=None, default=0, null=True)),
                ('recovered', models.IntegerField(blank=None, default=0, null=True)),
                ('death_rate', models.DecimalField(blank=None, decimal_places=2, default=0, max_digits=9, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_flag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='baseapp.DateFlag')),
                ('usa_state_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='baseapp.USAStateCode')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='usastateitem',
            unique_together={('date_flag', 'usa_state_code')},
        ),
    ]
