# Generated by Django 2.0.10 on 2020-03-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_comment_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='accumulated_comment_count',
            field=models.IntegerField(blank=None, default=0, null=True),
        ),
    ]
