# Generated by Django 2.0.10 on 2020-03-15 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20200315_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='total_view_count',
            field=models.BigIntegerField(blank=None, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='postview',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_views', to='forum.BlogPost'),
        ),
        migrations.AlterField(
            model_name='postviewip',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_view_ips', to='forum.BlogPost'),
        ),
    ]
